In [5]:
import pandas as pd

teamgoal = pd.read_csv("attempts_at_goal_team.csv")
fifateam = pd.read_csv("FIFA_Site_Team_Stats.csv")
matches = pd.read_csv("rounds.csv")

In [18]:
teamgoal.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 17 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   rank                              48 non-null     int64
 1   team_id                           48 non-null     int64
 2   team                              48 non-null     str
 3   team_abbrv                        48 non-null     str
 4   goals                             48 non-null     int64
 5   assists                           48 non-null     int64
 6   attempt_at_goal                   48 non-null     int64
 7   attempt_ontarget                  48 non-null     int64
 8   offtarget_attempt                 48 non-null     int64
 9   attempt_goal_convRate_percentage  48 non-null     int64
 10  attempt_inside_pa                 48 non-null     int64
 11  attempt_outside_pa                48 non-null     int64
 12  headed_attempt_goal               48 non-null     int64
 13  xG                                48 non-null     float64
 14  xG_efficiency                     48 non-null     str
 15  corners                           48 non-null     int64
 16  possession_control_percentage     48 non-null     int64
dtypes: float64(1), int64(13), str(3)
memory usage: 6.5 KB

In [14]:
teamgoal.head()

,rank,team_id,team,team_abbrv,goals,assists,attempt_at_goal,attempt_ontarget,offtarget_attempt,attempt_goal_convRate_percentage,attempt_inside_pa,attempt_outside_pa,headed_attempt_goal,xG,xG_efficiency,corners,possession_control_percentage
0,1,97,Spain,ESP,14,10,140,54,59,10,79,61,22,17.48,0.8x,54,58
1,2,19,France,FRA,20,18,139,59,59,14,77,62,10,16.78,1.19x,51,51
2,3,18,England,ENG,20,14,118,52,40,17,88,30,27,15.03,1.33x,40,50
3,4,2,Argentina,ARG,19,12,115,46,49,17,66,49,22,15.45,1.23x,41,53
4,5,5,Belgium,BEL,14,10,112,35,43,13,74,38,16,10.62,1.32x,24,46

In [19]:
teamgoal.describe()

,rank,team_id,goals,assists,attempt_at_goal,attempt_ontarget,offtarget_attempt,attempt_goal_convRate_percentage,attempt_inside_pa,attempt_outside_pa,headed_attempt_goal,xG,corners,possession_control_percentage
count,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000
mean,24.187500,46.666667,6.416667,4.645833,53.562500,18.479167,22.562500,11.229167,32.583333,20.979167,8.729167,5.533333,19.812500,44.333333
std,13.822055,37.125052,5.164664,4.128209,31.169343,13.473362,12.517063,5.482039,20.544537,12.543524,5.452852,4.204746,12.156176,8.213464
min,1.000000,1.000000,0.000000,0.000000,17.000000,2.000000,5.000000,0.000000,6.000000,6.000000,2.000000,1.120000,5.000000,27.000000
25%,12.500000,12.750000,2.000000,1.750000,31.750000,8.000000,14.750000,6.000000,16.750000,12.000000,5.000000,2.340000,10.000000,37.000000
50%,24.500000,48.500000,5.000000,3.000000,44.500000,14.000000,18.000000,11.500000,26.000000,18.000000,7.000000,4.260000,16.500000,46.000000
75%,34.750000,67.250000,10.000000,7.250000,69.250000,23.750000,28.250000,14.000000,44.750000,26.000000,12.000000,7.245000,26.000000,51.000000
max,47.000000,112.000000,20.000000,18.000000,140.000000,59.000000,59.000000,25.000000,88.000000,62.000000,27.000000,17.480000,54.000000,58.000000

In [15]:
fifateam.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Rank                                 48 non-null     int64
 1   Team                                 48 non-null     str
 2   Goals                                48 non-null     int64
 3   Assists                              48 non-null     int64
 4   Attempts_at_goal                     48 non-null     int64
 5   Attempts_on_target                   48 non-null     int64
 6   Off_Target_Attempts                  48 non-null     int64
 7   Attempts_ at_goal_conversionrate(%)  48 non-null     int64
 8   Attempts_Inside_PenaltyArea          48 non-null     int64
 9   Attemps_Outside_PenaltyArea          48 non-null     int64
 10  Headed_Attemps_at_Goal               48 non-null     int64
 11  xG                                   48 non-null     float64
 12  xG_Efficiency                        48 non-null     str
 13  Corners                              48 non-null     int64
 14  Possession_Control(%)                48 non-null     int64
dtypes: float64(1), int64(12), str(2)
memory usage: 5.8 KB

In [7]:
fifateam.head()

,Rank,Team,Goals,Assists,Attempts_at_goal,Attempts_on_target,Off_Target_Attempts,Attempts_ at_goal_conversionrate(%),Attempts_Inside_PenaltyArea,Attemps_Outside_PenaltyArea,Headed_Attemps_at_Goal,xG,xG_Efficiency,Corners,Possession_Control(%)
0,1,England,20,14,118,52,40,17,88,30,27,15.03,1.33x,40,50
1,1,France,20,18,139,59,59,14,77,62,10,16.78,1.19x,51,51
2,3,Argentina,19,12,115,46,49,17,66,49,22,15.45,1.23x,41,53
3,4,Spain,14,10,140,54,59,10,79,61,22,17.48,0.8x,54,58
4,4,Belgium,14,10,112,35,43,13,74,38,16,10.62,1.32x,24,46

In [20]:
fifateam.describe()

,Rank,Goals,Assists,Attempts_at_goal,Attempts_on_target,Off_Target_Attempts,Attempts_ at_goal_conversionrate(%),Attempts_Inside_PenaltyArea,Attemps_Outside_PenaltyArea,Headed_Attemps_at_Goal,xG,Corners,Possession_Control(%)
count,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000
mean,22.687500,6.416667,4.645833,53.562500,18.479167,22.562500,11.229167,32.583333,20.979167,8.729167,5.533333,19.812500,44.333333
std,13.184705,5.164664,4.128209,31.169343,13.473362,12.517063,5.482039,20.544537,12.543524,5.452852,4.204746,12.156176,8.213464
min,1.000000,0.000000,0.000000,17.000000,2.000000,5.000000,0.000000,6.000000,6.000000,2.000000,1.120000,5.000000,27.000000
25%,10.000000,2.000000,1.750000,31.750000,8.000000,14.750000,6.000000,16.750000,12.000000,5.000000,2.340000,10.000000,37.000000
50%,22.000000,5.000000,3.000000,44.500000,14.000000,18.000000,11.500000,26.000000,18.000000,7.000000,4.260000,16.500000,46.000000
75%,35.000000,10.000000,7.250000,69.250000,23.750000,28.250000,14.000000,44.750000,26.000000,12.000000,7.245000,26.000000,51.000000
max,48.000000,20.000000,18.000000,140.000000,59.000000,59.000000,25.000000,88.000000,62.000000,27.000000,17.480000,54.000000,58.000000

In [16]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 104 non-null    int64
 1   voteStatus         104 non-null    str
 2   stage              104 non-null    str
 3   roundName          104 non-null    str
 4   votingStartDate    104 non-null    str
 5   votingEndDate      104 non-null    str
 6   votingOpenedAt     104 non-null    str
 7   selectedFormation  2 non-null      str
 8   winners            104 non-null    str
 9   formations         2 non-null      str
 10  id.1               104 non-null    int64
 11  venueName          104 non-null    str
 12  venueCity          104 non-null    str
 13  venueId            104 non-null    int64
 14  date               104 non-null    str
 15  homeSquadId        104 non-null    int64
 16  awaySquadId        104 non-null    int64
 17  homeSquadName      104 non-null    str
 18  awaySquadName      104 non-null    str
 19  homeSquadAbbr      104 non-null    str
 20  awaySquadAbbr      104 non-null    str
 21  homeScore          104 non-null    int64
 22  awayScore          104 non-null    int64
 23  groupName          72 non-null     str
 24  matchDay           104 non-null    int64
dtypes: int64(8), str(17)
memory usage: 20.4 KB

In [8]:
matches.head()

,id,voteStatus,stage,roundName,votingStartDate,votingEndDate,votingOpenedAt,selectedFormation,winners,formations,...,homeSquadId,awaySquadId,homeSquadName,awaySquadName,homeSquadAbbr,awaySquadAbbr,homeScore,awayScore,groupName,matchDay
0,1,complete,group,round_1,2026-06-18T05:00:00+01:00,2026-06-20T05:00:00+01:00,2026-06-18T09:10:01+01:00,NaN,"[1844, 1987, 2267, 2571]",NaN,...,52,96,Mexico,South Africa,MEX,RSA,2,0,A,1
1,1,complete,group,round_1,2026-06-18T05:00:00+01:00,2026-06-20T05:00:00+01:00,2026-06-18T09:10:01+01:00,NaN,"[1844, 1987, 2267, 2571]",NaN,...,51,15,Korea Republic,Czechia,KOR,CZE,2,1,A,1
2,1,complete,group,round_1,2026-06-18T05:00:00+01:00,2026-06-20T05:00:00+01:00,2026-06-18T09:10:01+01:00,NaN,"[1844, 1987, 2267, 2571]",NaN,...,9,6,Canada,Bosnia and Herzegovina,CAN,BIH,1,1,B,1
3,1,complete,group,round_1,2026-06-18T05:00:00+01:00,2026-06-20T05:00:00+01:00,2026-06-18T09:10:01+01:00,NaN,"[1844, 1987, 2267, 2571]",NaN,...,111,58,USA,Paraguay,USA,PAR,4,1,D,1
4,1,complete,group,round_1,2026-06-18T05:00:00+01:00,2026-06-20T05:00:00+01:00,2026-06-18T09:10:01+01:00,NaN,"[1844, 1987, 2267, 2571]",NaN,...,60,99,Qatar,Switzerland,QAT,SUI,1,1,B,1

In [17]:
matches.describe()

,id,id.1,venueId,homeSquadId,awaySquadId,homeScore,awayScore,matchDay
count,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000,104.000000
mean,2.903846,52.500000,8.673077,46.692308,41.692308,1.721154,1.240385,2.913462
std,1.663540,30.166206,4.425088,37.793531,35.622093,1.503761,1.234576,1.695858
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
25%,2.000000,26.750000,5.000000,12.000000,11.000000,1.000000,0.000000,2.000000
50%,3.000000,52.500000,9.000000,49.500000,33.500000,1.000000,1.000000,3.000000
75%,4.000000,78.250000,13.000000,89.250000,58.000000,3.000000,2.000000,4.000000
max,8.000000,104.000000,16.000000,112.000000,112.000000,7.000000,6.000000,9.000000